name: Test for Password Strength

on:
  pull_request:
    branches:
      - main

jobs:
  password-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Set up dependencies
        run: npm install

      - name: Run password strength tests
        run: npm test -- src/tests/PasswordStrength.test.ts